### ISSUE TITLE
Clarifications re: 1. binning and 2. camera station/grating angle

### ISSUE THREAD

**Issue by svw26** [mattyowl/RSSMOSPipeline#10]
Hey,

1. I'd also like to clarify that '1x2' refers to a binning of '1' along the x axis (dispersion direction) and '2' along the y axis (spatial direction along the slit)? I assume so, given that our binning of '4 rows x 2 columns' gets written as "2x4" by the rss_mos_create_arc_model script.

Something I noticed whilst checking what a .pickle file is supposed to look like is that these ones appear like a normal text file when I view them using ```more filename.pickle```:
* RefModel_PG0900_Ar_2x2.pickle
* RefModel_PG0900_Ar_2x2_1.pickle
* RefModel_PG0900_Ne_2x2.pickle
* RefModel_PG0900_Ne_2x2_1.pickle
* RefModel_PG0900_Xe_2x2.pickle
* RefModel_PG1300_Ar_2x2.pickle
* RefModel_PG1300_Ar_2x2_1.pickle
* RefModel_PG1300_Cu Ar_2x2.pickle    [```more RefModel_PG1300_Cu\ Ar_2x2.pickle```]
* RefModel_PG1800_Ne_2x2.pickle

...whereas these (like the new RefModel_PG0900_Xe_2x4.pickle file) are interpreted as a binary file(?), with lots of funny characters appearing, making it look a mess:
* RefModel_PG0900_Ne_1x2.pickle
* RefModel_PG1300_Ar_1x2.pickle
* RefModel_PG1300_Ne_1x2.pickle

I thought maybe it's to do with the latter having non-standard binning. Or do you find that they're all fine? If so, then perhaps something 'extra' is happening for me because I'm going through a container...

2. The other thing I'd like to check is related to the README saying that each reference is for a particular combination of grating + lamp + detector binning. For the grating, is the camera station/grating angle just the default setting? e.g. for pg0900 the camera station is 31.75 deg and the grating angle is 15.875 deg?

The reason I'm asking is that photometric-redshift estimates were available for the SALT programme that Neo is working on, and so I made use of these to predict where we'd expect the emission lines to lie. [It would be annoying to observe such optically-faint sources for a long time only to find that the crucial line(s) coincided with a chip gap.] The downside is that means that Neo and I would need to make reference models for different combinations of pg0900 + lamp + 2x4 + grating angle, so I'm wondering whether the rss_mos_create_arc_model script could take that extra parameter (grating angle) into account? 

Many thanks,
Sarah x

**Comment by mattyowl** [comment]
Do you get any error message when using the .pickle files? If not, then there is no problem. Earlier versions might not have been saved in binary format, ones I made later were. The only time I had an issue with the included .pickle files was when switching from python2 -> python3. Since no one should be using python2 any more, I don't think there should be a problem.

> I'd also like to clarify that '1x2' refers to a binning of '1' along the x axis (dispersion direction) and '2' along the y axis (spatial direction along the slit)? I assume so, given that our binning of '4 rows x 2 columns' gets written as "2x4" by the rss_mos_create_arc_model script.

Yes, that's right - it's XxY.

> The other thing I'd like to check is related to the README saying that each reference is for a particular combination of grating + lamp + detector binning. For the grating, is the camera station/grating angle just the default setting? e.g. for pg0900 the camera station is 31.75 deg and the grating angle is 15.875 deg?

Grating angle shouldn't matter, most of the time - the code shifts + stretches the reference model to match your arc file in order to figure out the wavelength calibration. But the code will actually search multiple reference models (with suffixes __1.pickle, _2.pickle etc.) if they exist. Hence there are some lamp/grating/binning combinations with multiple models (I've been adding reference models as needed).

**Comment by svw26** [comment]
> Do you get any error message when using the .pickle files? If not, then there is no problem. Earlier versions might not have been saved in binary format, ones I made later were. 

Didn't get as far as picking up *any* .pickle files before, but saw your reply to issue #9 and it appears to be doing lots of stuff now!

> Grating angle shouldn't matter, most of the time - the code shifts + stretches the reference model to match your arc file in order to figure out the wavelength calibration. But the code will actually search multiple reference models (with suffixes __1.pickle, _2.pickle etc.) if they exist. Hence there are some lamp/grating/binning combinations with multiple models (I've been adding reference models as needed).

Okiedoke, thanks. Was wondering what the suffixes meant :) x
