### ISSUE TITLE
Splrep woes

### ISSUE THREAD

**Issue by nechnotick** [mattyowl/RSSMOSPipeline#12]
Hi Matt,

Hope that all is well with you.

I get an splrep error when running the updated master on a particular target, with threshold set at 1. This doesn't happen however when the threshold is not invoked. Please help :(

Neo
![Screenshot from 2021-03-29 20-40-33](https://user-images.githubusercontent.com/43254022/112991231-2d252480-9167-11eb-9afd-513d562ea270.png)

**Comment by mattyowl** [comment]
Hi Neo,

The threshold (with -T) is set in terms of sigma, and defaults to 2. Are you sure you want a 1-sigma threshold? Are you finding it is not detecting some object trace that you want? Some very faint object?

Probably it'll be easiest for me to get to the bottom of this if you can put the data somewhere for me to take a look (just for this object - the arc files, flats, and the object frames).

Cheers
Matt

**Comment by mattyowl** [comment]
You can put the data anywhere and then send the link (via email, not on here). e.g., google drive, dropbox, or on some webserver at Rhodes? It'll be too big to attach on GitHub I guess.

**Comment by nechnotick** [comment]
Cool, many thanks. 
I have just shared the folder with hiltonm@ukzn.ac.za.

**Comment by mattyowl** [comment]
With the default settings, it's picking up 3 traces, and SLIT3 is presumably your target object? You're wanting to get the faint traces at the top of the image below?

![image](https://user-images.githubusercontent.com/8531799/113265753-c9b90500-92d4-11eb-9fbd-5518aede1404.png)

**Comment by mattyowl** [comment]
Anyway, with -T 1 this fails for SLIT5 (which would be at the top) because the wavelength solution it gets is completely wacky. But its only picking up 6 features in the arc for most of these, which might be why. Which makes me think making a new Xe arc for this might solve it. I can do that, since I have the data from you.

**Comment by mattyowl** [comment]
Ok, this was failing for SLIT4, not SLIT5. Adding a new arc didn't help.

Anyway, I've fixed it such that it doesn't drop into IPython when the wavelength calib/rectification step fails - it just issues a warning. So it'll run to completion but SLIT4 will be blank for your data. SLIT5 (right at the top) works ok though (Halpha indicates z = 0.094).

Changes are checked into the master branch, if you want to give it a go. I should put a new release on PyPI at some point soon...

**Comment by nechnotick** [comment]
Cool, thanks!
