### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by nechnotick** [mattyowl/RSSMOSPipeline#16]
Something weird is happening -- running "rss_mos_reducer product reduced all" returns "rss_mos_reducer: command not found", even after pip installing the pipeline.

**Comment by mattyowl** [comment]
Which platform / OS etc. is this on, and how are you running pip? Installing system-wide or in a user directory?

If using Ubuntu, then if you install as a regular user like this:

`pip3 install RSSMOSPipeline`

then scripts are installed under `$HOME/.local/bin`, which may not be in your `PATH`. To fix that, you need to do:

`export PATH=$HOME/.local/bin:$PATH`

which you need to add to e.g. `.bashrc` if you want it to be permanent.

**Comment by nechnotick** [comment]
Thanks, that was very helpful.
