### ISSUE TITLE
Labelling unmarked streaks

### ISSUE THREAD

**Issue by nechnotick** [mattyowl/RSSMOSPipeline#18]
Hi Matt,

Hope that you are well. 

The pipeline seems to have trouble picking up slits that are of interest to us and we were wondering if there was a way to highlight these, as some of them can be spotted with an unaided eye?

As always your help is greatly appreciated.

Regards,
Neo

**Comment by mattyowl** [comment]
Hi Neo,

Have you played with the -T switch for rss_mos_reducer? That sets the detection threshold (in sigma) for the algorithm that looks for traces. You can try setting it to a lower value and see if that helps.

Cheers
Matt

**Comment by nechnotick** [comment]
Hi Matt,

I had already set the threshold to 1 for the targets in question.

Regards,
Neo

**Comment by mattyowl** [comment]
Ok, well the routine that finds the object traces is here:

https://github.com/mattyowl/RSSMOSPipeline/blob/d01661f0a252143c4c5058ea7eb43c52dfee78ad/RSSMOSPipeline/RSSMOSTools.py#L676

Maybe you can take a look at it and tweak it and/or figure out why it isn't picking up the objects you want? It's a very short bit of code.

You don't need to run this in the pipeline to see what it does - you can write a python script and just feed it one of your image file names.

Cheers
Matt

**Comment by nechnotick** [comment]
Tweaking the numbers in the aforementioned code does not yield any change to the output. Is there another way around this?

Neo
